{
 "title": "AoP",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Connection Counter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(amqp_connection_counter)" }
   ]
  },
  {
   "title": "VHost Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vhost_count) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Exchange Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(exchange_count) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(queue_count) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Exchange Read Failed Counter",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(exchange_read_failed_counter) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Exchange Read Failed Counter",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(exchange_read_failed_counter) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Queue Read Failed Counter",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "sum(queue_read_failed_counter) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Exchange Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(exchange_write_counter{}[30s])) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Exchange Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(exchange_read_counter{}[30s])) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Exchange Ack Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(exchange_ack_counter{}[30s])) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Exchange Write Failed Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "sum(exchange_write_failed_counter) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Queue Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(queue_publish_counter{}[30s])) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Queue Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(queue_read_counter{}[30s])) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Queue Ack Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(queue_ack_counter{}[30s])) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Queue Write Failed Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "sum(queue_publish_failed_counter) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Exchange Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(exchange_write_latency_seconds_bucket[30s])) by (le)) * 1000",
     "legendFormat": "pt90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(exchange_write_latency_seconds_bucket[30s])) by (le)) * 1000",
     "legendFormat": "pt95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(exchange_write_latency_seconds_bucket[30s])) by (le)) * 1000",
     "legendFormat": "pt99"
    }
   ]
  },
  {
   "title": "Exchange Read Latency (pt90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(exchange_read_latency_seconds_bucket[30s])) by (le)) * 1000",
     "legendFormat": "pt90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(exchange_read_latency_seconds_bucket[30s])) by (le)) * 1000",
     "legendFormat": "pt95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(exchange_read_latency_seconds_bucket[30s])) by (le)) * 1000",
     "legendFormat": "pt99"
    }
   ]
  },
  {
   "title": "Exchange Route Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(exchange_route_counter{}[30s])) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Exchange Route Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(exchange_route_latency_bucket[30s])) by (le)) * 1000",
     "legendFormat": "pt90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(exchange_route_latency_bucket[30s])) by (le)) * 1000",
     "legendFormat": "pt95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(exchange_route_latency_bucket[30s])) by (le)) * 1000",
     "legendFormat": "pt99"
    }
   ]
  },
  {
   "title": "Queue Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(queue_write_latency_seconds_bucket[30s])) by (le)) * 1000",
     "legendFormat": "pt90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(queue_write_latency_seconds_bucket[30s])) by (le)) * 1000",
     "legendFormat": "pt95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(queue_write_latency_seconds_bucket[30s])) by (le)) * 1000",
     "legendFormat": "pt99"
    }
   ]
  },
  {
   "title": "Queue Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(queue_read_latency_seconds_bucket[30s])) by (le)) * 1000",
     "legendFormat": "pt90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(queue_read_latency_seconds_bucket[30s])) by (le)) * 1000",
     "legendFormat": "pt95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(queue_read_latency_seconds_bucket[30s])) by (le)) * 1000",
     "legendFormat": "pt99"
    }
   ]
  }
 ]
}